pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat label: '', script: '''
                echo "I am in Build step"
                gradlew build
                '''
            }
        }
        stage('Test')
        {
            steps {
                bat script: '''
                    echo "I am in Test step"
                    gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                bat script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                bat script: '''
                    echo "I am Building DockerImage ="
                    docker build . -t "mars_rover"
                    echo "Done"
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                bat script: '''
                    echo "I am Publishing DockerImage ="
                    docker login -u=shivani08 -p=$Hivani08
                    docker tag mars_rover shivani08/image_final
                    docker push shivani08/image_final
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
	post
	{
		always{
			deleteDir()
		}
	}
}