pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh label: '', script: '''
                echo "I am in Build step"
                chmod 777 ./gradlew
                ./gradlew build
                '''
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    chmod 777 ./gradlew
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage"
                    ./docker build . -t "mars_rover_image"
                    ./docker run "mars_rover_image"
                    echo "Done"
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Publishing DockerImage ="
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
	post
	{
		always{
			deleteDir()
		}
	}
}